<?php

return [
    'roles' => [
        ['name' => 'User', 'slug' => 'user', 'level' => 1],
        ['name' => 'Moderator', 'slug' => 'moderator', 'level' => 2],
        ['name' => 'Admin', 'slug' => 'admin', 'level' => 3],
    ],
    'statuses' => [
        [
            'type' => 'account',
            'slug' => 'normal',
            'name' => 'Active',
            'reason' => 'Account is active',
        ],
        [
            'type' => 'account',
            'slug' => 'ban',
            'name' => 'Banned',
            'reason' => 'Account is banned',
        ],
        [
            'type' => 'post',
            'slug' => 'normal',
            'name' => 'Published',
            'reason' => 'Post is published',
        ],
        [
            'type' => 'review',
            'slug' => 'ban',
            'name' => 'Banned',
            'reason' => 'Review is banned',
        ],
        [
            'type' => 'post',
            'slug' => 'ban',
            'name' => 'Banned',
            'reason' => 'Post is banned',
        ],
        [
            'type' => 'review',
            'slug' => 'normal',
            'name' => 'Published',
            'reason' => 'Review is published',
        ],
        [
            'type' => 'post',
            'slug' => 'hidden',
            'name' => 'Hidden',
            'reason' => 'Post is hidden',
        ],
    ],
    'categories' => [
        'Thời sự và Tin tức Toàn cầu',
        'Dân sinh',
        'Lao động và Việc làm',
        'Giao thông',
        'Chính trị Xã hội',
        'Y tế',
        'Giáo dục',
        'Nghiên cứu',
        'Môi trường',
        'Văn hóa và Nghệ thuật',
        'Lịch sử và Di sản Văn hóa',
        'Sách',
        'Quân sự',
        'Pháp luật',
        'Thể thao',
        'Giải trí',
        'Du lịch',
        'Thế giới',
        'Khoa học',
        'Xe',
        'Đời sống hàng ngày',
        'Blockchain và Tiền điện tử',
        'Công nghệ',
    ],
    'hashtags' => [
        'Khoa học và Công nghệ',
        'Sức khỏe và Y tế',
        'Kinh doanh và Tài chính',
        'Chính trị và Xã hội',
        'Môi trường và Bảo vệ tự nhiên',
        'Văn hóa và Nghệ thuật',
        'Giáo dục và Nghiên cứu',
        'Đời sống hàng ngày',
        'Du lịch và Phiêu lưu',
        'Công nghệ Blockchain và Tiền điện tử',
        'Thể thao và Giải trí',
        'Điện tử Tiêu dùng và Công nghệ gia đình',
        'Phát triển Nghệ thuật và Thiết kế',
        'Chăm sóc Động vật và Quyền Động vật',
        'Lịch sử và Di sản Văn hóa',
        'Du lịch và Phiêu lưu',
        'Thảo luận Xã hội và Vấn đề Xã hội',
        'Nghiên cứu khoa học và Phát triển',
        'Sách và Văn hóa Đọc',
        'Chăm sóc Sức khỏe Tâm thần',
        'Thời sự và Tin tức Toàn cầu ',
    ],
    'userBanned' => [
        'slug' => 'ban',
        'type' => 'account',
    ],
];
